defmodule Tunez.Repo.Migrations.UniqueAlbumNamesPerArtist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:albums, [:artist_id, :name],
             name: "albums_unique_album_name_per_artist_index"
           )
  end

  def down do
    drop_if_exists unique_index(:albums, [:artist_id, :name],
                     name: "albums_unique_album_name_per_artist_index"
                   )
  end
end
