defmodule Tunez.Repo.Migrations.AddGinIndexForArtistSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:artists, ["(name gin_trgm_ops)"], name: "artists_name_gin_index")

    create index(:artists, ["name gin_trgm_ops"], name: "artists_name_gin_index", using: "GIN")
  end

  def down do
    drop_if_exists index(:artists, ["name gin_trgm_ops"], name: "artists_name_gin_index")

    create index(:artists, ["(name gin_trgm_ops)"], name: "artists_name_gin_index", using: "GIN")
  end
end
